target 'MVVMCoordinator' do
  
  
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  # Pods for MVVM+Coordinator

end